namespace StockNotifications.Models.ExternalApis.RapidApiYahooFinance
{
    public class QuoteResult
    {
        public string Language { get; set; }
        public string Region { get; set; }
        public string QuoteType { get; set; }
        public string QuoteSourceName { get; set; }
        public bool Triggerable { get; set; }
        public QuoteSummary QuoteSummary { get; set; }
        public string Currency { get; set; }
        public double TrailingPe { get; set; }
        public double PegRatio { get; set; }
        public double DividendsPerShare { get; set; }
        public double Revenue { get; set; }
        public double PriceToSales { get; set; }
        public string MarketState { get; set; }
        public double EpsTrailingTwelveMonths { get; set; }
        public double EpsForward { get; set; }
        public double EpsCurrentYear { get; set; }
        public double EpsNextQuarter { get; set; }
        public double PriceEpsCurrentYear { get; set; }
        public double PriceEpsNextQuarter { get; set; }
        public int SharesOutstanding { get; set; }
        public double BookValue { get; set; }
        public double FiftyDayAverage { get; set; }
        public double FiftyDayAverageChange { get; set; }
        public double FiftyDayAverageChangePercent { get; set; }
        public double TwoHundredDayAverage { get; set; }
        public double TwoHundredDayAverageChange { get; set; }
        public double TwoHundredDayAverageChangePercent { get; set; }
        public long MarketCap { get; set; }
        public double ForwardPe { get; set; }
        public double PriceToBook { get; set; }
        public int SourceInterval { get; set; }
        public int ExchangeDataDelayedBy { get; set; }
        public string ExchangeTimezoneName { get; set; }
        public string ExchangeTimezoneShortName { get; set; }
        public QuotePageViews QuotePageViews { get; set; }
        public int GmtOffSetMilliseconds { get; set; }
        public bool EsgPopulated { get; set; }
        public bool Tradeable { get; set; }
        public long FirstTradeDateMilliseconds { get; set; }
        public int PriceHint { get; set; }
        public double TotalCash { get; set; }
        public int FloatShares { get; set; }
        public long Ebitda { get; set; }
        public double ShortRatio { get; set; }
        public double TargetPriceHigh { get; set; }
        public double TargetPriceLow { get; set; }
        public double TargetPriceMean { get; set; }
        public double TargetPriceMedian { get; set; }
        public double HeldPercentInsiders { get; set; }
        public double HeldPercentInstitutions { get; set; }
        public double PostMarketChangePercent { get; set; }
        public int PostMarketTime { get; set; }
        public double PostMarketPrice { get; set; }
        public double PostMarketChange { get; set; }
        public double RegularMarketChange { get; set; }
        public double RegularMarketChangePercent { get; set; }
        public int RegularMarketTime { get; set; }
        public double RegularMarketPrice { get; set; }
        public double RegularMarketDayHigh { get; set; }
        public string RegularMarketDayRange { get; set; }
        public double RegularMarketDayLow { get; set; }
        public int RegularMarketVolume { get; set; }
        public int SharesShort { get; set; }
        public int SharesShortPrevMonth { get; set; }
        public double ShortPercentFloat { get; set; }
        public double RegularMarketPreviousClose { get; set; }
        public double Bid { get; set; }
        public double Ask { get; set; }
        public int BidSize { get; set; }
        public int AskSize { get; set; }
        public string Exchange { get; set; }
        public string Market { get; set; }
        public string MessageBoardId { get; set; }
        public string FullExchangeName { get; set; }
        public string ShortName { get; set; }
        public string LongName { get; set; }
        public double RegularMarketOpen { get; set; }
        public int AverageDailyVolume3Month { get; set; }
        public int AverageDailyVolume10Day { get; set; }
        public double Beta { get; set; }
        public double FiftyTwoWeekLowChange { get; set; }
        public double FiftyTwoWeekLowChangePercent { get; set; }
        public string FiftyTwoWeekRange { get; set; }
        public double FiftyTwoWeekHighChange { get; set; }
        public double FiftyTwoWeekHighChangePercent { get; set; }
        public double FiftyTwoWeekLow { get; set; }
        public double FiftyTwoWeekHigh { get; set; }
        public int EarningsTimestamp { get; set; }
        public int EarningsTimestampStart { get; set; }
        public int EarningsTimestampEnd { get; set; }
        public string[] Components { get; set; }
        public string Symbol { get; set; }
    }
}